set -g terminal-overrides '*:Tc'
set -g destroy-unattached on
set -g exit-empty on
set -g mouse on
unbind-key -a

set-option -g default-shell /usr/bin/fish

bind -n C-t new-window
bind -n C-w kill-window
bind -n C-PageDown next-window
bind -n C-PageUp previous-window
bind -n C-S-PPage swap-window -t -1 \; select-window -t -1
bind -n C-S-NPage swap-window -t +1 \; select-window -t +1

set -g prefix C-a
unbind C-b

set -g status-bg black
set -g status-fg white

set -g window-status-style fg=colour4,bg=#262f48
set -g window-status-current-style fg=colour2,bg=#3a4b37
set -g window-status-separator ""  

set -g window-status-format " #[bold]#I #W "
set -g window-status-current-format " #[bold]#I #W "

set -g status-left ""
set -g status-right " #[bold]%H:%M "
set -g status-position top
set -g allow-rename off
